#!/bin/bash
rm -rf data
mkdir -p data
fno_list_Arr=$(cat fno_main.json | jq ".[]" | jq ".[].symbol" | fzf --reverse -m -i --height=80%);
arr=($fno_list_Arr)


final="["
for i in "${arr[@]}"
do
  final=$final"{\"label\": $i, \"value\": $i} ,"
done

final=${final::-1}"]"
 
echo $final
echo $final > fno.json

python3 optionchain.py

# rm -f fno.json

# sxiv -t data/outputs/*/.
